<script setup>
import {reactive,watch} from 'vue'
const props=defineProps({resource:String,initialData:{type:Object,default:null},lookups:{type:Object,default:()=>({})}})
const emit=defineEmits(['submit','cancel'])
const form=reactive({})
const configs={
  provinces:[['name','Tên tỉnh thành','text'],['code','Mã tỉnh thành','text'],['active','Trạng thái','boolean']],
  stations:[['provinceId','Tỉnh thành','select','provinces'],['name','Tên bến','text'],['address','Địa chỉ','text'],['phone','Điện thoại','text',null,true],['latitude','Vĩ độ','number',null,true],['longitude','Kinh độ','number',null,true],['active','Trạng thái','boolean']],
  vehicles:[['licensePlate','Biển số','text'],['name','Tên xe','text'],['type','Loại xe','enum',['SLEEPER','LIMOUSINE','SEATER']],['totalSeats','Số ghế','number'],['floors','Số tầng','number'],['imageUrl','Ảnh xe','text',null,true],['active','Trạng thái','boolean']],
  routes:[['code','Mã tuyến','text'],['name','Tên tuyến','text'],['originStationId','Bến đi','select','stations'],['destinationStationId','Bến đến','select','stations'],['distanceKm','Khoảng cách (km)','number'],['durationMinutes','Thời gian (phút)','number'],['basePrice','Giá cơ bản','number'],['active','Trạng thái','boolean']],
  trips:[['code','Mã chuyến','text'],['routeId','Tuyến đường','select','routes'],['vehicleId','Xe','select','vehicles'],['driverId','Tài xế','select','users',true],['departureTime','Giờ đi','datetime-local'],['arrivalTime','Giờ đến','datetime-local'],['price','Giá vé','number'],['boardingNote','Ghi chú','text',null,true],['status','Trạng thái','enum',['SCHEDULED','BOARDING','RUNNING','FINISHED','CANCELLED']]],
  promotions:[['code','Mã giảm','text'],['name','Tên','text'],['type','Loại','enum',['PERCENT','FIXED']],['value','Giá trị','number'],['maxDiscount','Giảm tối đa','number',null,true],['minOrderAmount','Đơn tối thiểu','number',null,true],['usageLimit','Lượt dùng','number',null,true],['startAt','Bắt đầu','datetime-local',null,true],['endAt','Kết thúc','datetime-local',null,true],['active','Trạng thái','boolean']],
  addons:[['name','Tên dịch vụ','text'],['description','Mô tả','text',null,true],['price','Giá','number'],['icon','Icon','text',null,true],['active','Trạng thái','boolean']],
  'trip-stops':[['tripId','Chuyến xe','select','trips'],['stationId','Bến dừng','select','stations'],['stopOrder','Thứ tự','number'],['arrivalTime','Giờ đến','datetime-local'],['departureTime','Giờ đi','datetime-local'],['pickupAllowed','Cho phép đón','boolean'],['dropoffAllowed','Cho phép trả','boolean']]
}
const fields=()=>configs[props.resource]||[]
const relationKeys={provinceId:'province',originStationId:'originStation',destinationStationId:'destinationStation',routeId:'route',vehicleId:'vehicle',driverId:'driver',tripId:'trip',stationId:'station'}
function localDateTime(value){return value?String(value).slice(0,16):''}
function fill(){Object.keys(form).forEach(k=>delete form[k]);fields().forEach(([key,,type,,optional])=>{let value=props.initialData?.[key];if(value==null&&relationKeys[key])value=props.initialData?.[relationKeys[key]]?.id;if(type==='datetime-local')value=localDateTime(value);if(value!=null)form[key]=value;else if(type==='boolean')form[key]=key==='active'||key==='pickupAllowed'||key==='dropoffAllowed';else form[key]=optional?null:''})}
watch([()=>props.resource,()=>props.initialData],fill,{immediate:true,deep:true})
function optionName(item,source){if(source==='stations')return `${item.name}${item.province?.name?' — '+item.province.name:''}`;if(source==='routes')return `${item.code} — ${item.name}`;if(source==='vehicles')return `${item.licensePlate} — ${item.name}`;if(source==='trips')return `${item.code} — ${item.route?.name||''}`;if(source==='users')return `${item.fullName||item.email}${item.role?' — '+item.role:''}`;return item.name||item.code||('#'+item.id)}
function submit(){const payload={...form};fields().filter(f=>f[2]==='number'||f[2]==='select').forEach(([key])=>{if(payload[key]!==''&&payload[key]!=null)payload[key]=Number(payload[key]);else payload[key]=null});fields().filter(f=>f[4]).forEach(([key])=>{if(payload[key]==='')payload[key]=null});if(!props.initialData&&props.resource!=='provinces')delete payload.active;if(!props.initialData&&props.resource==='trips')delete payload.status;if(props.resource==='routes'&&payload.originStationId===payload.destinationStationId)return alert('Bến đi và bến đến phải khác nhau');emit('submit',payload)}
</script>
<template><form class="resource-form card" @submit.prevent="submit"><h3>{{initialData?'Chỉnh sửa dữ liệu':'Thêm dữ liệu mới'}}</h3><label v-for="field in fields()" :key="field[0]">{{field[1]}}<select v-if="field[2]==='select'" v-model="form[field[0]]" :required="!field[4]"><option :value="field[4]?null:''">{{field[4]?'Không chọn':'-- Chọn '+field[1].toLowerCase()+' --'}}</option><option v-for="item in lookups[field[3]]||[]" :key="item.id" :value="item.id">{{optionName(item,field[3])}}</option></select><select v-else-if="field[2]==='enum'" v-model="form[field[0]]" required><option value="">-- Chọn --</option><option v-for="item in field[3]" :key="item" :value="item">{{item}}</option></select><select v-else-if="field[2]==='boolean'" v-model="form[field[0]]"><option :value="true">Đang hoạt động / Có</option><option :value="false">Đã tắt / Không</option></select><input v-else v-model="form[field[0]]" :type="field[2]" :step="field[2]==='number'?'any':undefined" :required="!field[4]"></label><div class="form-actions"><button class="btn primary">{{initialData?'Lưu thay đổi':'Thêm mới'}}</button><button type="button" class="btn" @click="emit('cancel')">Hủy</button></div></form></template>
<style scoped>.form-actions{display:flex;gap:10px;align-items:center}.resource-form h3{grid-column:1/-1;margin:0 0 4px}.resource-form label{font-size:12px;font-weight:600}.resource-form select,.resource-form input{width:100%;margin-top:7px;border:1px solid #dce5f0;border-radius:9px;padding:12px;background:#fff}</style>
