<script setup>
import {computed,onMounted,ref,watch} from 'vue';import {useRouter} from 'vue-router';import {publicApi} from '../../api/publicApi.js';import {bookingApi} from '../../api/bookingApi.js';import {money,date} from '../../api/client.js';import {useAuth} from '../../stores/auth.js';import {useToast} from '../../stores/toast.js';import SeatMap from '../../components/SeatMap.vue';import LoadingState from '../../components/LoadingState.vue';
const props=defineProps({tripId:{type:String,required:true}}),router=useRouter(),auth=useAuth(),toast=useToast();const trip=ref(null),seats=ref([]),selected=ref([]),passengers=ref([]),step=ref(1),busy=ref(false);const total=computed(()=>selected.value.length*(trip.value?.price||0));
watch([()=>selected.value.length,trip],()=>{passengers.value=selected.value.map((id,i)=>passengers.value[i]||{fullName:auth.user.value?.fullName||'',phone:auth.user.value?.phone||'',email:auth.user.value?.email||'',tripSeatId:id})});
function toggle(seat){selected.value=selected.value.includes(seat.id)?selected.value.filter(id=>id!==seat.id):[...selected.value,seat.id]}
async function load(){try{[trip.value,seats.value]=await Promise.all([publicApi.trip(props.tripId),publicApi.seats(props.tripId)])}catch(e){toast.show(e.message)}}
async function submit(){if(!auth.user.value){toast.show('Vui lòng đăng nhập trước khi đặt vé');return router.push({path:'/auth',query:{redirect:router.currentRoute.value.fullPath}})}if(passengers.value.some(p=>!p.fullName||!/^0\d{9}$/.test(p.phone)))return toast.show('Vui lòng nhập đúng họ tên và số điện thoại');busy.value=true;try{const booking=await bookingApi.create({tripId:Number(props.tripId),passengers:passengers.value,paymentMethod:'VNPAY'});localStorage.setItem('last_booking',booking.bookingCode);if(!booking.paymentUrl?.startsWith('https://sandbox.vnpayment.vn/'))throw new Error('Backend chưa tạo được URL VNPay Sandbox hợp lệ');window.location.assign(booking.paymentUrl)}catch(e){toast.show(e.message)}finally{busy.value=false}}onMounted(load);
</script>
<template><LoadingState v-if="!trip" text="Đang tải sơ đồ ghế..."/><section v-else class="figma-booking"><header class="booking-bar"><button v-if="step>1" @click="step--">←</button><h2>{{step===1?'Chọn ghế':step===2?'Thông tin hành khách':'Thanh toán VNPay'}}</h2></header><div class="booking-journey"><span class="bus-thumb">🚌</span><div><b>{{trip.vehicle.name}}</b><small>{{date(trip.departureTime)}}</small></div><strong>{{new Date(trip.departureTime).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'})}}</strong><i></i><strong>{{new Date(trip.arrivalTime).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'})}}</strong><small>{{trip.origin.name}} → {{trip.destination.name}}</small></div><div class="booking-stage"><SeatMap v-if="step===1" :seats="seats" :selected="selected" @toggle="toggle"/><div v-else-if="step===2" class="passenger-panel"><h3>Thông tin hành khách</h3><div v-for="(passenger,index) in passengers" :key="passenger.tripSeatId" class="passenger"><b>Hành khách {{index+1}} · Ghế {{seats.find(s=>s.id===passenger.tripSeatId)?.number}}</b><div class="form-grid"><label>Họ và tên<input v-model="passenger.fullName"></label><label>Số điện thoại<input v-model="passenger.phone"></label><label>Email<input v-model="passenger.email" type="email"></label></div></div></div><div v-else class="payment-panel"><h3>Thanh toán</h3><p>Bạn sẽ được chuyển sang cổng VNPay Sandbox để thanh toán thử.</p><label class="pay-option active"><input type="radio" checked disabled><b>VNPay Sandbox</b><strong>VNPAY</strong></label></div></div><footer class="booking-bottom"><div><small>Đã chọn ({{selected.length}} ghế)</small><b>{{selected.map(id=>seats.find(s=>s.id===id)?.number).join(', ')||'—'}}</b></div><div><small>Tổng tiền</small><strong>{{money(total)}}</strong></div><button v-if="step<3" class="btn primary" :disabled="!selected.length" @click="step++">Tiếp tục</button><button v-else class="btn primary" :disabled="busy" @click="submit">{{busy?'Đang xử lý...':'Thanh toán VNPay'}}</button></footer></section></template>
