<script setup>
import {computed,onMounted,reactive,ref} from 'vue';import {useRouter} from 'vue-router';import {publicApi} from '../../api/publicApi.js';import {useToast} from '../../stores/toast.js';import TripCard from '../../components/TripCard.vue';
const router=useRouter(),{show}=useToast(),stations=ref([]),trips=ref([]),upcomingTrips=ref([]),loading=ref(true),searched=ref(false);
const form=reactive({origin:'',destination:'',date:new Date(Date.now()+86400000).toISOString().slice(0,10),passengers:1});
const filters=reactive({type:'',maxPrice:'',departure:'all'});
const shown=computed(()=>trips.value.filter(t=>(!filters.type||t.vehicle.type===filters.type)&&(!filters.maxPrice||t.price<=Number(filters.maxPrice))&&matchTime(t.departureTime)));
const originName=computed(()=>stations.value.find(s=>String(s.id)===String(form.origin))?.province||'Điểm đi');
const destinationName=computed(()=>stations.value.find(s=>String(s.id)===String(form.destination))?.province||'Điểm đến');
function matchTime(value){if(filters.departure==='all')return true;const h=new Date(value).getHours();return filters.departure==='morning'?h<12:filters.departure==='afternoon'?h<18:h>=18}
async function load(){loading.value=true;try{[stations.value,upcomingTrips.value]=await Promise.all([publicApi.stations(),publicApi.trips({})])}catch(e){show(e.message)}finally{loading.value=false}}
async function search(){if(!form.origin||!form.destination)return show('Vui lòng chọn điểm đi và điểm đến');if(form.origin===form.destination)return show('Điểm đi và điểm đến phải khác nhau');loading.value=true;searched.value=true;try{trips.value=await publicApi.trips({origin:form.origin,destination:form.destination,date:form.date})}catch(e){show(e.message)}finally{loading.value=false}}
onMounted(load);
</script>
<template><main class="customer-home">
  <template v-if="!searched">
    <section class="ft-hero"><div class="ft-hero-copy"><h1>Đặt vé xe dễ dàng<br>– Nhanh chóng</h1><p>Đặt vé online, chọn ghế, thanh toán<br>dễ dàng cùng FastTravel.</p></div><img src="/bus-hero.svg" alt="Xe khách FastTravel" class="hero-bus"></section>
    <form class="figma-search" @submit.prevent="search"><span class="search-tab">Vé xe</span><div class="search-fields"><label><small>Điểm đi</small><select v-model="form.origin"><option value="">Chọn điểm đi</option><option v-for="s in stations" :key="s.id" :value="s.id">{{s.province}} — {{s.name}}</option></select></label><button type="button" class="swap" @click="[form.origin,form.destination]=[form.destination,form.origin]">⇄</button><label><small>Điểm đến</small><select v-model="form.destination"><option value="">Chọn điểm đến</option><option v-for="s in stations" :key="s.id" :value="s.id">{{s.province}} — {{s.name}}</option></select></label><label><small>Ngày đi</small><input v-model="form.date" type="date"></label><label><small>Số hành khách</small><select v-model.number="form.passengers"><option v-for="n in 6" :key="n" :value="n">{{n}} hành khách</option></select></label></div><button class="btn primary search-submit">Tìm chuyến xe</button></form>
    <section class="figma-benefits"><article><i>✓</i><div><b>Đặt vé nhanh chóng</b><small>Chọn chuyến, chọn ghế,<br>thanh toán chỉ trong vài phút</small></div></article><article><i>▣</i><div><b>Nhiều nhà xe uy tín</b><small>Hợp tác với nhiều nhà xe<br>chất lượng trên toàn quốc</small></div></article><article><i>▤</i><div><b>Thanh toán an toàn</b><small>Thanh toán thử an toàn qua<br>VNPay Sandbox</small></div></article><article><i>◷</i><div><b>Hỗ trợ 24/7</b><small>Đội ngũ hỗ trợ luôn sẵn sàng<br>giải đáp mọi thắc mắc</small></div></article></section>
    <section class="upcoming-section"><div class="deal-title"><div><h2>Chuyến xe sắp khởi hành</h2><p>Các chuyến còn ghế và vẫn trong thời hạn đặt vé</p></div></div><div v-if="loading" class="empty">Đang tải chuyến xe...</div><div v-else-if="upcomingTrips.length" class="upcoming-list"><TripCard v-for="trip in upcomingTrips" :key="trip.id" :trip="trip" @choose="id=>router.push('/booking/'+id)"/></div><div v-else class="empty upcoming-empty">Hiện chưa có chuyến xe tương lai.</div></section>
  </template>
  <section v-else class="search-results-page"><div class="results-heading"><div><h1>{{originName}} <span>→</span> {{destinationName}}</h1><p>Ngày đi: {{new Date(form.date).toLocaleDateString('vi-VN')}}　|　{{form.passengers}} hành khách</p></div><button class="outline-btn" @click="searched=false">Thay đổi tìm kiếm</button></div><div class="results-layout"><aside class="filter-panel"><div class="filter-title"><b>Bộ lọc</b><button @click="filters.type='';filters.maxPrice='';filters.departure='all'">Xóa lọc</button></div><h3>Giờ khởi hành</h3><label><input v-model="filters.departure" type="radio" value="all"> Tất cả</label><label><input v-model="filters.departure" type="radio" value="morning"> Trước 12:00</label><label><input v-model="filters.departure" type="radio" value="afternoon"> 12:00 – 18:00</label><label><input v-model="filters.departure" type="radio" value="evening"> Sau 18:00</label><h3>Khoảng giá</h3><select v-model="filters.maxPrice"><option value="">Tất cả mức giá</option><option value="200000">Dưới 200.000đ</option><option value="400000">Dưới 400.000đ</option></select><h3>Loại xe</h3><label><input v-model="filters.type" type="radio" value=""> Tất cả loại xe</label><label><input v-model="filters.type" type="radio" value="SLEEPER"> Giường nằm</label><label><input v-model="filters.type" type="radio" value="LIMOUSINE"> Limousine</label><label><input v-model="filters.type" type="radio" value="SEATER"> Ghế ngồi</label></aside><div class="results-list"><div v-if="loading" class="empty">Đang tìm chuyến xe...</div><TripCard v-for="trip in shown" v-else :key="trip.id" :trip="trip" @choose="id=>router.push('/booking/'+id)"/><div v-if="!loading&&!shown.length" class="empty">Không tìm thấy chuyến phù hợp.</div></div></div></section>
</main></template>
